ERROR 2019-11-10 19:53:49,898 root : Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fddd04e0bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR 2019-11-10 21:53:54,300 root : Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fadcd7b9c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR 2019-11-10 21:54:14,462 root : Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f74406f7b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR 2019-11-10 21:55:14,528 root : Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f744135f910>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR 2019-11-10 21:55:25,377 root : Exception: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc35d0bdb50>: Failed to establish a new connection: [Errno 111] Connection refused'))
